config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task_item.rb
class TaskItem < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task_item = TaskItem.new()
    @task_items = TaskItem.all()
  end
  
  def create
    @task_item = TaskItem.new(task_item_params)
    
    if @task_item.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  def edit
    @task_item = TaskItem.find(params[:id])
  end
  
  def update
    @task_item = TaskItem.find(params[:id])
    @task_item.update(task_item_params)
    redirect_to root_path
  end
  
  def destroy
    @task_item = TaskItem.find(params[:id])
    @task_item.destroy()
    redirect_to root_path
  end
  
  private
  def task_item_params
    params.require(:task_item).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div>
  <h2>タスクの編集</h2>
  <%= form_for @task_item, url: {action: 'update'} do |f| %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.submit "保存", class: 'btn-block btn-white' %>
  <% end %>
  
  <%= link_to '一覧に戻る', root_path %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<div>
  <h2>新規タスク</h2>
  <%= form_for @task_item, url: {action: 'create'} do |f| %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.submit "追加", class: 'btn-block btn-white' %>
  <% end %>
  
  <h3>タスクリスト</h2>
  <ul>
    <% @task_items.each do |task_item| %>
      <li>
        <%= task_item.title %>
        <%= link_to "編集", edit_task_path(task_item) %>
        <%= link_to "削除", task_path(task_item), method: :delete, data: {confirm: '本当に削除していいですか？'} %>
      </li>
    <% end %>
  </ul>
</div>